language: ruby
gemfile:
  - gemfiles/rails_7_devise_4.gemfile
  - gemfiles/rails_6_devise_4.gemfile
rvm:
  - "1.9.3"
  - "2.6.3"
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_7_devise_4.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_6_devise_4.gemfile
install: bundle install --jobs=3 --retry=3 --no-deployment
sudo: false
